# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 06:24
from __future__ import unicode_literals

import core.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20160314_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(15), core.models.validate_duration])),
                ('note', models.TextField()),
                ('done_at', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-done_at'],
                'verbose_name_plural': 'absences',
            },
        ),
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'reasons',
            },
        ),
        migrations.AlterField(
            model_name='progress',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
        migrations.AddField(
            model_name='absence',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AbsenceReason'),
        ),
        migrations.AddField(
            model_name='absence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
