# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160511_0624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbsenceReason',
            new_name='Absentia',
        ),
    ]
