# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160515_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='reason',
            new_name='absentia',
        ),
    ]
