# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 11:27
from __future__ import unicode_literals

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160515_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='duration',
            field=models.IntegerField(default=480, validators=[django.core.validators.MinValueValidator(15), core.models.validate_duration]),
        ),
    ]
