# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161106_1011'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tajmuser',
            table=None,
        ),
    ]
