# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 13:49
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20161111_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='amount',
            field=models.IntegerField(blank=True, null=True, validators=[core.models.validate_duration]),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='starts_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
