# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 13:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161111_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
