# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20161111_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadline',
            old_name='amount',
            new_name='hour_amount',
        ),
    ]
