# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160515_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absentia',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='absence',
            name='started_at',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
