# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160515_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absentia',
            new_name='AbsenceCategory',
        ),
        migrations.RenameField(
            model_name='absence',
            old_name='absentia',
            new_name='category',
        ),
    ]
