"""
Django settings for semirhage project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from semirhage.settings import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-0jr90^zs@lr(0ysg05vj6rm^@#d^)r_ybqt=$jq6itm#n0sm7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['reborn.tajm.me']

HTML_MINIFY = True
